version: '3.8'

services: 
  client: 
    container_name: client
    build: 
      context: ./client
      dockerfile: ./dockerfile
    ports:
     - '3000:3000'
  server: 
    restart: always
    container_name: server
    build:
      context: ./server
      dockerfile: ./dockerfile
    ports:
      - '3030:3030'
    env_file:
      - ./server/docker.env
    depends_on: 
      - database
  database:
    container_name: database
    image: 'postgres:14'
    ports:
      - '5432:5432'
    env_file:
      - ./server/docker.env
    volumes:
      - ./.database/postgres/data:/data/extra